name: 'Particle Compile'
description: 'Compiles application source code'
inputs:
  particle-platform-name:
    required: true
    description: 'The platform name to target the compilation. Example: photon, p1, electron, argon, asom, boron'
    default: ''
  particle-access-token:
    required: false
    description: 'Particle access token. If provided, the action will use the Particle Cloud Compiler instead of compiling within the GitHub Action runner'
    default: ''
  device-os-version:
    required: false
    description: 'Target Device OS firmware version. Allowed values: default, latest, latest-lts, or a semver version number. Example: latest, latest-lts, 4.x, ^5.3.0, 1.4.4'
    default: 'default'
  sources-folder:
    required: false
    description: 'Path to directory with sources to compile. Example: src'
    default: '.'
  auto-version:
    required: false
    description: 'If true, the action will automatically increment the product firmware version. See AUTO_VERSION.md for more details.'
    default: 'false'
  auto-version-macro-name:
    required: false
    description: 'Name of the macro that contains the product firmware version.'
    default: 'PRODUCT_VERSION'
outputs:
  firmware-path:
    description: 'Path to the compiled firmware binary file.'
  target-path:
    description: 'Path to the folder with compiled firmware files and their associated object files. The folder includes the firmware binary, ELF, HEX, and MAP files, along with object files. Not available when particle-access-token is set (cloud compile).'
  device-os-version:
    description: 'This output contains the actual Device OS version used for compilation.'
  firmware-version:
    description: 'The product firmware version integer. This output is undefined when sources are not a product firmware.'
  firmware-version-updated:
    description: 'Boolean value indicating whether the product firmware version was updated. Can only be true with auto-version enabled.'
runs:
  using: 'node20'
  main: 'dist/index.js'
