name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:


jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
      - run: |
          npm run all
  test-cloud-compile:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: 'Cloud compile'
        with:
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}
          particle-platform-name: 'argon'
          sources-folder: 'test/fixtures/single-file-firmware'
  test-auto-version:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Verify product version is 100'
        run: |
          cat test/fixtures/product-firmware/application.cpp | grep -q 'PRODUCT_VERSION(100);'
      - uses: ./
        name: 'Bump product version and compile'
        with:
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}
          particle-platform-name: 'boron'
          sources-folder: 'test/fixtures/product-firmware'
          device-os-version: 'latest-lts'
          auto-version: 'true'
      - name: 'Verify product version is 101'
        run: |
          cat test/fixtures/product-firmware/application.cpp | grep -q 'PRODUCT_VERSION(101);'
  test-local-compile:
    strategy:
      matrix:
        # note - local compile only works on linux
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: 'Local compile'
        with:
          particle-platform-name: 'argon'
          sources-folder: 'test/fixtures/single-file-firmware'
