name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:


jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-cloud-compile:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: 'Cloud compile'
        with:
          particle_access_token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}
          particle_platform_name: '12'
          sources_folder: '__tests__/fixtures'
  test-local-compile:
    strategy:
      matrix:
        # note - local compile only works on linux
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: 'Local compile'
        with:
          particle_platform_name: '12'
          sources_folder: '__tests__/fixtures'
